#test ci
branches:
  only:
  - master
  - watch_pull_request_with_travis

language: java
jdk:
  - oraclejdk8

env:
  CATALINA_BASE=/home/travis

sudo: false
install: true

script:
  - mvn install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
